USE Airlines226
GO

CREATE PROCEDURE phantom_reads_t1 AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- SERIALIZABLE
	BEGIN TRY
		BEGIN TRAN
		WAITFOR DELAY '00:00:03'
		INSERT INTO Flights VALUES (1, 4, CURRENT_TIMESTAMP, 100)
		INSERT INTO log_table VALUES ('INSERT', 'Flights', CURRENT_TIMESTAMP)

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
	END CATCH
END
GO

CREATE PROCEDURE phantom_reads_t2 AS
BEGIN
	BEGIN TRY
		BEGIN TRAN
		SELECT * FROM Flights
		INSERT INTO log_table VALUES('SELECT', 'Flight', CURRENT_TIMESTAMP)
		WAITFOR DELAY '00:00:10'
		SELECT * FROM Flights
		INSERT INTO log_table VALUES('SELECT', 'Flight', CURRENT_TIMESTAMP)
		COMMIT TRAN

		PRINT 'Transaction commited'
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT 'Transaction rollbacked'
	END CATCH
END

EXEC phantom_reads_t1
EXEC phantom_reads_t2

DROP PROCEDURE phantom_reads_t1
DROP PROCEDURE phantom_reads_t2

