USE politie
GO

CREATE PROCEDURE deadlock_t1 AS
BEGIN 
	BEGIN TRAN
	BEGIN TRY
		UPDATE Politisti SET nume='Ion' WHERE id=1
		WAITFOR DELAY '00:00:05'
		UPDATE Programari SET data=CURRENT_TIMESTAMP WHERE id=1
		COMMIT TRAN
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		PRINT ERROR_MESSAGE()
	END CATCH
END
GO

CREATE PROCEDURE deadlock_t2 AS
BEGIN 
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
	-- SET DEADLOCK_PRIORITY HIGH
	SET DEADLOCK_PRIORITY LOW
	BEGIN TRAN
	BEGIN TRY

		UPDATE Politisti SET nume='Ion' WHERE id=1
		WAITFOR DELAY '00:00:05'
		UPDATE Programari SET data=CURRENT_TIMESTAMP WHERE id=1

		COMMIT TRAN
	END TRY
	BEGIN CATCH
		PRINT ERROR_MESSAGE()
		ROLLBACK TRAN
	END CATCH
END

EXEC deadlock_t1

CREATE NONCLUSTERED INDEX NX_Politisti_Nume_Prenume ON Politisti(nume ASC, prenume DESC)
ALTER INDEX NX_Politisti_Nume_Prenume ON Politisti DISABLE

SELECT * FROM Politisti ORDER BY nume